### ISSUE TITLE
no such column: displayName

### ISSUE THREAD

**Issue by SLEEPLisNight** [david-laundav/Android-CalendarService#3]
android.database.sqlite.SQLiteException: no such column: displayName: , while compiling: SELECT _id, displayName, selected FROM Calendars

**Comment by david-laundav** [comment]
Could you be more specific?

I havn't heard about this issue from anyone else and the service has furthermore been tested on multiple devices already.

Could you possibly answer the following questions?
1. Which phone do you use for development (and SDK)?
2. How do you use the service?
3. Could you supply your code?

Thanks in advance

**Comment by SLEEPLisNight** [comment]
1. Galaxy Nexus.
2. Used the source code directly by creating the CalendarService class.
3. I just copy paste your code, which includes two classes: CalendarEvent and CalendarService.
   and I use them by this one line: CalendarService.readCalendar(getContext(), 10, 0);

And I got error message like the one above.

**Comment by david-laundav** [comment]
Thanks.

After some research I found, that Android has changed its public calendar API from 4.0+ (ICS). This lead to a couple of changes, including the removal of the "displayName" which was old convention (apparently). This leads to some frustration since it will be difficult to support older devices if I were to change the library.

http://android-developers.blogspot.dk/2011/10/ics-and-non-public-apis.html

Although, what you can try to do, is to change the "displayName" to "CALENDAR_DISPLAY_NAME" which is the new convention accordingly to:

http://developer.android.com/guide/topics/providers/calendar-provider.html

I hope this helps, and please let me know whether or not it works out for you.

Thanks once more for the feedback :+1:

**Comment by SLEEPLisNight** [comment]
android.database.sqlite.SQLiteException: no such column: CALENDAR_DISPLAY_NAME: , while compiling: SELECT _id, CALENDAR_DISPLAY_NAME, selected FROM Calendars

**Comment by david-laundav** [comment]
Thanks.

It seems weird that you receive the same error upon correcting the code accordingly to API 4.0+. 

I will probably have to do some investigation at some point, to find out how to resolve this specific issue. 

Please do not hesitate to write me if you find a solution yourself; I will obviously give you a huge credit for doing so.

Till then, I hope you can at least use my library for inspirational purposes.

**Comment by SLEEPLisNight** [comment]
Apparently, this worked for me: 
Cursor cursor = contentResolver.query(Uri.parse("content://com.android.calendar/events"), new String[]{ "calendar_id", "title", "description", "dtstart", "dtend", "eventLocation" }, null, null, null);

**Comment by david-laundav** [comment]
Ah, so rather than using "calendar" you are using the "events" Uri. If it seems to work for you, I will add it as a comment in my code.

Can I type your account name into a Credits section of the readme?

Thanks a lot!

**Comment by SLEEPLisNight** [comment]
sure, thanks!

**Comment by pro-sunny** [comment]
Please note also, that in eventCursor you have to change 
Calendars._id
to
Events.calendar_id
in that case
